api/urls.py
from django.urls import include,path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'users',views.UserViewSet)
router.register(r'products',views.ProductViewSet)





urlpatterns = [
    path('',include(router.urls)),
    # path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    # path('product/',views.product_api),
]

myapp/urls.py
from django.urls import path,include
from .views import ProductDelete,ProductUpdateView,ProductDetailView,ProductListView, add_to_cart,index,new_one,products,product_details,add_product, show_cart,update_product,delete_product
from . import views
app_name = 'myapp'

urlpatterns = [
    path('',index),
    path('new/',new_one),
    # path('products/',products,name='products'),
    path('products/',ProductListView.as_view(), name='products'),
    # path('products/<int:id>',product_details,name='product_details'),
    path('products/<int:pk>',ProductDetailView.as_view(), name='product_details'),
    path('products/add',add_product,name='add_product'),
    # path('products/update/<int:id>',update_product,name='update_product'),
    path('products/update/<int:pk>',ProductUpdateView.as_view(), name='update_product'),
    # path('products/delete/<int:id>',delete_product,name='delete_product'),
    path('products/delete/<int:pk>',ProductDelete.as_view(), name='delete_product'),
    path('products/add-to-cart/',add_to_cart, name='add-to-cart'),
    path('products/cart/',show_cart, name='showcart'),
    path('products/checkout/',show_cart, name='checkout')
    



]   

mysite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include

from myapp.views import index,new_one
from django.conf.urls.static import static

from mysite import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    
    
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('api/',include('api.urls')),
    
    
        
]


urlpatterns  += static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from .views import register,profile,create_profile,seller_profile
from django.contrib.auth import views as authentication_views


app_name = 'users'


urlpatterns = [
   
    path('register/',register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',profile,name='profile'),
    path('createprofile/', create_profile,name='createprofile'),
    path('sellerprofile/<int:id>',seller_profile,name='sellerprofile')
   
] 

myapp/models.py
# from unittest.util import max_length
# from enum import unique
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100,unique=True)
    price = models.FloatField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True,upload_to='images')
    seller_name = models.ForeignKey(User,on_delete=models.CASCADE)
    
    
    
    
class Cart(models.Model):
    name = models.CharField(max_length=100,unique=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    price = models.FloatField()
    description = models.CharField(max_length=200)


    
    
    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price
    

myapp/views.py
from itertools import product
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView,DetailView,CreateView,DeleteView,UpdateView
from myapp.admin import ProductAdmin
from myapp.models import Product,Cart
from django.urls import reverse_lazy
# Create your views here.-


def index(request):
    d = {
        "name": "Arun",
        "age" : 30,
        
    }
    
    li = ["Allen","Alwin","Sreerag","Allu"]
    
    for i in range(0,10):
      print(i)
      
    context = {'li':li}
    
    
    return render(request, 'myapp/index.html',context=context)


def new_one(request):
    return render(request, 'listing/new_one.html')

class ProductListView(ListView):
    model = Product
    template_name = 'myapp/products.html'
    context_object_name = 'products'

@login_required
def products(request):
    p = Product.objects.all()
    
    context = {'products':p}
    
    return render(request, 'myapp/products.html',context=context)


def product_details(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
    return render(request, 'myapp/product_details.html',context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/product_details.html'
    context_object_name = 'p'


@login_required
def add_product(request):
    if request.method == 'POST':
     name=request.POST.get('name')
     price=request.POST.get('price')
     desc=request.POST.get('desc')
     image=request.FILES['upload']
     
     
     
     p = Product(name=name,price=price,description=desc,image=image)
     p.seller_name = request.user
     p.save()
     
     
     return redirect('/myapp/products')
     
         
    return render(request,'myapp/add_product.html')



def update_product(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
   
   
    if request.method == 'POST':
     p.name = request.POST.get('name')
     p.price = request.POST.get('price')
     p.description = request.POST.get('desc')
    
     
     try:
         p.image = request.FILES['upload']
     except:
         pass
     
    #  p = Product(name=name,price=price,description=desc,image=image)
    
     p.save()
     
     
     
     return redirect('/myapp/products')
     
         
    return render(request,'myapp/update_product.html',context = context)



class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name','price','description','image','seller_name']
    template_name = 'myapp/update_product.html'
    context_object_name = 'p'
    success_url = reverse_lazy('myapp:products')






def delete_product(request,id):
    p = Product.objects.get(id=id)
    context = {'p':p}
   
   
    if request.method == 'POST':
        p.delete()
        return redirect('/myapp/products')
     
         
    return render(request,'myapp/delete_product.html',context = context)


class ProductDelete(DeleteView):
    model = Product
    template_name = 'myapp/delete_product.html'
    context_object_name = 'p'
    success_url = reverse_lazy('myapp:products')
    
    
    
    



def add_to_cart(request):
    p = Product.objects.get(id=id)
    user=request.user
    product = Product.objects.get(id=id)
    Cart(user=user,product=product).save()
    return redirect("myapp/cart")
    

def show_cart(request):
    user = request.user
    cart = Cart.objects.filter(user=user)
    return render(request, 'myapp/addtocart.html',locals())

myapp/templates/myapp/add_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Add Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" placeholder="Name" type="text" name="name"
            id="name">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" placeholder="Price" type="text"
            name="price" id="price">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Description</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" placeholder="Description" type="text"
            name="desc" id="desc">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Image</label>
        <input type="file" name="upload" id="upload">
    </div>
    <div class="mb-5">
        <input
            class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus-ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark focus-ring-grren-800"
            type="submit" accept="imagee/*" name="Add Product" value="Add product">
    </div>

</form>
{% endblock %}

myapp/templates/myapp/base.html
{% load static tailwind_tags %}
<html data-theme="light">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>

<body>
    
        <div class="navbar bg-base-100 drop-shadow-md">
            <div class="flex-1">
                <a class="btn btn-ghost normal-case text-xl">Mysite Cart</a>
            </div>
            <div class="flex-none">
                <div class="dropdown dropdown-end">
                    <label tabindex="0" class="btn btn-ghost btn-circle">
                        <div class="indicator">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                            <span class="badge badge-sm indicator-item">8</span>
                        </div>
                    </label>
                    <div tabindex="0" class="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow">
                        <div class="card-body">
                            <span class="font-bold text-lg">8 Items</span>
                            <span class="text-info">Subtotal: $999</span>
                            <div class="card-actions">
                                <button class="btn btn-primary btn-block">View cart</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="dropdown dropdown-end z=20">
                    <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                        <div class="w-10 rounded-full">
                            <img src="https://placeimg.com/80/80/people" />
                        </div>
                    </label>
                    <ul tabindex="0"
                        class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                        <li>
                            <a class="justify-between">
                                Profile
                                <span class="badge">New</span>
                            </a>
                        </li>
                        <li><a>Settings</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    


    {% block content %}
    
    
    
    {% endblock  %}


</body>

</html>

myapp/templates/myapp/delete_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">🗑️Delete Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Name : {{p.name}}</label>
            
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Price : {{p.price}}</label>
            
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Description : {{p.description}}</label>
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Image</label>
        <img class="w=36 mb=3 rounded-lg" src="{{p.image.url}}" alt="Image not found">
    </div>
    <div class="mb-5">
        <input class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus-ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark focus-ring-grren-800"
            type="submit" accept="imagee/*" name="Add Product" value="Delete product">
    </div>

</form>
{% endblock %}

myapp/templates/myapp/index.html
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<>>, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2 style="color: brown;">Hello Myapp</h2>
    <ol>
        {% for n in li %}
        <li>
            <h1 style="color: brown;">{{n}}</h1>
        </li>
        {% endfor %}


    </ol>
</body>

</html>

myapp/templates/myapp/product_details.html
{% extends "myapp/base.html" %}

{% block content %}


<!--<div class="card w-50 p-30 center">
  <img class="w-2/5" src="{{p.image.url}}" alt="Denim Jeans" style="width:100%">
  <h1>{{p.name}}</h1>
  <p class="price">₹ {{p.price}}</p>
  <p>{{p.description}}<br></p>
  <br>
  <br>
</div> -->
<div class="flex p=10 w-full h-200 bg-purple-50"><br>
  <img class="w-1/3 rounded-xl" src="{{p.image.url}}" alt="unable to load image">
  <div class="w-2/3 text-xl ml-10 font-bold">
    <div class="mt-10 text-black-700">ID:{{p.id}}</div><br>
    <div class="mt-10 text-black-400">Name:{{p.name}}</div><br>
    <div class="mt-10 text-black-400">Description:{{p.description}}</div><br>
    <div class="mt-10 text-black-700">Price:{{p.price}}</div><br>
   
      <a href="{% url 'users:sellerprofile' p.seller_name.id %}">
      <div class="text-sm"><b>Seller Details</b></div>
      
    </a>
    <form action="/add-to-cart" class="d-inline">
      <input type="hidden" name="product_id" value="{{p.id}}"/>
      <button type="submit" class="btn btn-primary shadow px-5 py-2">Add To Cart</button>
    </form>
   
</div>

{% endblock %}

myapp/templates/myapp/products.html
{% extends "myapp/base.html" %}

{% block content %}

  <div class="container align-center justify-center mx-auto px-6 grid grid-cols-2 grid-flow-row gap-5  z=30 place-content-center">



    {% for p in products %}
    <div class="card w-96 glass ">
      <figure><img class="object-cover h-60 w-90" src="{{p.image.url}}" alt="Something went Wrong" /></figure>
      <div class="card-body">
        <h2 class="card-title">{{p.name}}</h2>
        <p>{{p.description}}</p>
        <div class="card-actions justify-end">
          <a href="{% url 'myapp:product_details' p.id %}">
          <button class="btn btn-primary">₹ {{p.price}}</button>
        </a>
        </div>
      </div>
    </div>



   {% comment %} <div class="box-content h-65 w-32 p-4 border-4 rounded-xl"> -->
      <h2 style="text-align:center">Product Card</h2>
      <a href="{% url 'product_details' p.id %}">
        <div class="card">
          <img class="" src="{{p.image.url}}" alt="Image not found" style="width:200px">
          <h1 class="text-sky-500">{{p.name}}</h1>
          <p class="price">₹ {{p.price}}</p>
          <p>{{p.description}}<br></p>
          <br> 
          <br>
        </div>
      </a>
    </div>  {% endcomment %}


    {% endfor %}
  </div>
 
  {% endblock %}

myapp/templates/myapp/update_product.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Update Product</h1>
<form class="w-2/5 shadow-md m-10 p-10" method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" value="{{p.name}}" placeholder="Name" type="text" name="name" id="name">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" value="{{p.price}}" placeholder="Price" type="text" name="price" id="price">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Description</label>
        <input class="appearance-none shadow broder rounded-lg text-grey-800" value="{{p.description}}" placeholder="Description" type="text" name="desc" id="desc">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2" for="">Product Image</label>
        <img class="w-36 mb-3 rounded-lg" src="{{p.image.url}}" alt="Image not found">
        <input type="file" name="upload" id="upload">
    </div>
    <div class="mb-5">
<input class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus-ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark focus-ring-grren-800" type="submit" accept="imagee/*" name="Update Product" value="Update product">
</div>

</form>
{% endblock %} 